### ISSUE TITLE
Can this tool calculate the THD vs Time of a "chirp" waveform

### ISSUE THREAD

**Issue by abrahamcn** [endolith/waveform-analysis#15]
Can this tool get the THD vs Time of a "chirp" waveform?

**Comment by endolith** [comment]
Not really, no.  If the chirp is slow enough, you could run it through the THD function in small chunks, though.

**Comment by endolith** [comment]
@abrahamcn

Is there anything you need from me on this it can I close it?

I think you would need a different algorithm to process actual sweep signals. Stepped sweep signals should work fine as long as you process chunks less than one step.
