### ISSUE TITLE
how to use thdcalculator.py?

### ISSUE THREAD

**Issue by peterpain1216** [endolith/waveform-analysis#24]
when i entered 
:python3 thdcalculator.py mytestfile.wav,  nothing happened.

then i use:
python3 thd_analyzer_launcher.py mytestfile.wav, i got this error:

Exception:
name 'analyze_channels' is not defined

sorry for being a noob, how to use the scripts properly?  thanks

**Comment by peterpain1216** [comment]
python3 wave_analyzer_launcher.py mytestfile.wav

this script works fine for me.

**Comment by endolith** [comment]
You mean the older `thdncalculator.py` here?  https://gist.github.com/endolith/246092

**Comment by endolith** [comment]
Yeah it appears to not be finished, sorry. I'm not sure why I pushed it that way.  For now you can load the WAV into an array and process it with THDN() https://github.com/endolith/waveform_analysis/blob/master/waveform_analysis/thd.py#L44  and it will return the ratio.

**Comment by endolith** [comment]
Or just use the old version: https://gist.github.com/endolith/246092

**Comment by endolith** [comment]
This is fixed in baece1e
