### ISSUE TITLE
THD calculation

### ISSUE THREAD

**Issue by williamszy** [endolith/waveform-analysis#26]
THD = sum([abs(f[i*x]) for x in range(2, 15)]) / abs(f[i])
THD shall be the root-mean-square value of all harmonics?

**Comment by ftab** [comment]
@endolith this repo shows up near the top of a search for "python thd calculation", which is how I got here (feels like 95% of my job is knowing what to google on bing). Least trustworthy or not, it's apparently more useful/used than the alternatives. ;)

**Comment by endolith** [comment]
@ftab  I know.  😑  I really need to spend some time cleaning it up.

**Comment by ftab** [comment]
I'm no good at math, but if you want me to do some busy work, I'd be happy to help!
