### ISSUE TITLE
Pass frequency as an argument

### ISSUE THREAD

**Issue by khaut** [endolith/waveform-analysis#36]
Thank you for your fantastic work in this wonderful code :)

I was working with a simple audio measurement tool and tried your code to get THD / THD+N values. It seems to work nice (althought I haven't verified the results) but realized that it would be nice to pass sine generator frequency in realtime measurements. I have sine generator (python script) running through sounddevice stream so I know what frequency to expect as fundamental. As my lab environment is nowhere perfect and working with breadboard, frequency estimator can sometimes mistakingly think that 50Hz is fundamental etc.

In this case it would be nice to have an option to pass frequency as an argument from signalgenerator and use that for measurements instead.

Thanks again!

**Comment by endolith** [comment]
Yes I've been thinking that would be good to have too.

**Comment by endolith** [comment]
Does the latest change work for you?

**Comment by khaut** [comment]
Thank you for this!

I did quick test and it seems to work as expected :) I only tested with pipewire loopback but I will test with analog I/O soon and I will report here if I notice something.

I realized that I had modified THD function "return" on thd.py and returned also "frequency", "fundamental amplitude" and "harmonics array" so I could draw fancy bargraphs from harmonics like I've seen somewhere as well as detected frequency. So I need to test that I'm not messing things up.

**Comment by endolith** [comment]
I was also making changes to optionally output the list of harmonics, but wasn't sure about the output format.  Can you show me yours?

**Comment by endolith** [comment]
Here's my version: https://github.com/endolith/waveform-analysis/compare/verbose_return_harmonics

**Comment by khaut** [comment]
Passing frequency as argument works. I just tested with noisy signal.

**Comment by khaut** [comment]
> @khaut I was also making changes to optionally output the list of harmonics, but wasn't sure about the output format. Can you show me yours?

Now I'm returning :

    return THD, frequency, fundLevel, harmonic_amplitudes

I just wanted to change as little as possible. Works but probably could be nicer.
Earlier I included fundLevel as index 0 of harmonic_amplitudes for Db value calculations. Frequency is returned ´ just to save CPU cycles if it's allready calculated and I want to know/show it.

**Comment by khaut** [comment]
When doing testing I noticed that there is possibility for "IndexError" if frequency is low and estimation goes on the wrong side.

```
waveform_analysis/thd.py", line 235, in THD
    ampl = abs(f[i * h])    # if i * h <= len(f):
               ~^^^^^^^
IndexError: index 6006 is out of bounds for axis 0 with size 6001
```

I've tried to use that "if ..."  (in the comment on the same line) to check and that helped, but maybe there is better way to do it. I trust on your python skills more than mine :)

**Comment by endolith** [comment]
@khaut Can you post that as a separate issue instead of a comment on this closed issue?

**Comment by khaut** [comment]
I will. Thanks!
